handler:
  type: function
  runtime: nodejs
  source: tools/fetch_webpage.js
definition:
  type: function
  function:
    name: fetch_webpage
    description: Fetch a webpage and return the HTML content.
    parameters:
      type: object
      properties:
        url:
          type: string
          description: URL of the webpage to fetch.
      required:
        - url
