delegate: !include config/tools/delegate.yml
fetch_webpage: !include config/tools/fetch_webpage.yml
get_context: !include config/tools/get_context.yml
get_team_roster: !include config/tools/get_team_roster.yml
goodbye: !include config/tools/goodbye.yml
message_team_member: !include config/tools/message_team_member.yml
mkdir: !include config/tools/mkdir.yml
open: !include config/tools/open.yml
read_dir: !include config/tools/read_dir.yml
read_file: !include config/tools/read_file.yml
set_context: !include config/tools/set_context.yml
write_file: !include config/tools/write_file.yml
shell_exec: !include config/tools/shell_exec.yml
